runtime: nodejs22

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 0
  max_instances: 10

handlers:
- url: /public
  static_dir: public

- url: /admin
  static_dir: admin

- url: /.*
  script: auto
